version: '3'

services:
  app:
    image: fund-management
    container_name: fund-management-container
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://amvelasquez9621:R0OIy4R9uB0ka32O@clusterfundmanagement.rftpv.mongodb.net/?retryWrites=true&w=majority&appName=ClusterFundManagement
    ports:
      - "8060:8060"
    networks:
      - backend

networks:
  backend:
    driver: bridge
